package com.mola.molablogv2.repository;

import com.mola.molablogv2.pojo.BlogType;
import com.mola.molablogv2.pojo.example.BlogTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BlogTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    long countByExample(BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int deleteByExample(BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int insert(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int insertSelective(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    List<BlogType> selectByExample(BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    BlogType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlogType record, @Param("example") BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlogType record, @Param("example") BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    List<BlogType> selectAll();
}