spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 314
    url: jdbc:mysql://127.0.0.1/molablog?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource


    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  jackson:
    default-property-inclusion: non_null

  #模板引擎
  thymeleaf:
    cache: false
    check-template: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
  #关闭默认图标
  mvc:
    favicon:
      enabled: false

server:
  servlet:
    context-path: /molablog
    session:
      timeout: 180m
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mola.molablogv2.pojo

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  #只允许本机的9001端口操作监控
  server:
    port: 9012
    address: 127.0.0.1

#个人配置
my-conf:
  rootPath: /home/mola/molablog-app

#邮件配置
emailConf:
  mailHost : smtp.sohu.com
  #邮件协议
  mailTransportProtocol : smtp
  #是否可信
  mailSmtpAuth : true
  #user
  userName : molablog
  #password
  password : molablog123456
  #port
  port : 465



